### ISSUE TITLE
树形结构不合理

### ISSUE THREAD

**Issue by yahvk-cuna** [SadPencil/mo3-mod-manager#1]
例如，我做了一个任务，那我应该依赖`MO-330` 还是 `MO-333`。
或者别人发布了一个任务，依赖 `MO-333` 我该怎么用 `MO-333-ZH-CN` 来玩。

应该做成自由组合，在自由组合上再加上依赖关系。
`MO-333` _require_ `MO-330`，`MO-330` 和 `MO-333` 都 _provide_ `MO`，这样，任务只需要 _require_ `MO`，用户任意选一个 _proivde_ `MO` 的都可以满足依赖。
这样也可以同时装多个 Mod，比如像音乐包这样的 Mod。

**Comment by SadPencil** [comment]
感谢你的提议。考虑过这样的想法，还是因为时间问题作罢。
这个软件目前并没有得到战役作者、汉化包作者等的支持，绝大多数人用“沉默”回应了我“希望他们发布战役时按指定格式制作一键安装包”的请求。因此，在没有得到这些人的支持之前，本着经济的原则，不会有对软件进行大规模更新的想法。
如果你想让这个软件做得更好，可以选择劝说任务作者按格式制作一键安装包，劝说制作游戏集合包的人用它代替“游戏安装包”等，让软件真正“用”起来。或者，软件根据 MIT 许可协议开源，你可以按照自己的意思对它进行修改、再发行。

**Comment by yahvk-cuna** [comment]
战役作者不懂 JSON 吧……
你做个一键生成器会更好
就询问下名字和文件路径，id 可以从名字生成，其他的保持默认，直接生成可以被使用的 zip 文件

**Comment by SadPencil** [comment]
不懂 JSON 也没啥，就是改个字符串而已

**Comment by yahvk-cuna** [comment]
战役作者不知道怎么改啊，你就给个 example.zip，很多人不明白吧

**Comment by SadPencil** [comment]
下载地址里一直提供着 EXAMPLE-MISSION.ZIP

**Comment by yahvk-cuna** [comment]
你就给个 EXAMPLE-MISSION.ZIP，很多人不明白吧

**Comment by SadPencil** [comment]
不光是这个 ZIP 文件，我在 B站 也提供了说明视频，位于 av30239702 的最后。

**Comment by yahvk-cuna** [comment]
打个 _won't fix_ 吧
